### ISSUE TITLE
Investigar se a gem kmeans realmente agrupa corretamente.

### ISSUE THREAD

**Issue by absaldanha** [play-it/play-it#11]

**Comment by absaldanha** [comment]
Mudou a gem para a `kmeans-clusterer`, mas ainda tem que gerar uma certa certeza que os agrupamentos estão certos.

**Comment by nmdoliveira** [comment]
Você já não fez isso?

**Comment by absaldanha** [comment]
Acho que sim kk

**Comment by nmdoliveira** [comment]
Vou fechar então u.u
