### ISSUE TITLE
Verificar o erro com a path para o library.dat

### ISSUE THREAD

**Issue by absaldanha** [play-it/play-it#20]
Resolver o problema do caminho para o library.dat, em que só está funcionando com `./libary.dat` e não com o caminho completo no sistema.

**Comment by nmdoliveira** [comment]
É problema do `fakefs`

**Comment by nmdoliveira** [comment]
Funcionou tirando o `fakefs`, ainda não sabemos por quê, mas vai ficar assim mesmo porque não temos tempo para investigar isso agora.
